# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

#    - name: vuepress-deploy
#      uses: jenkey2011/vuepress-deploy@master
#      env:
#        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        TARGET_REPO: Skillz4Killz/Discordeno
#        TARGET_BRANCH: gh-pages
#        BUILD_SCRIPT: cd docs && npm i && npm run docs:build
#        BUILD_DIR: docs/.vuepress/dist/
#        CNAME: discordeno.js.org
